# Required
version: 2

# Build config
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

# Configuration
python:
  version: 3.11
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
