site_name: AI on Demand
site_url: https://aiondemand.github.io/aiondemand
theme:
  name: material
  features:
    - content.code.copy
nav:
  - Introduction: 'README.md'
  - API: 'api/reference.md'
  - 'changelog.md'
  - 'contributing.md'
  - 'conduct.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings

