[tool.poetry]
name = "aiod_py_sdk"
version = "0.1.0"
description = "Python SDK for the AIoD metadata ctathalogue"
authors = ["Jean Matias"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
