[project]
name = "aiondemand"
version = "1.0.2"
description = "Python SDK for the AIoD metadata catalogue"
authors = [
    { name="Jean Matias", email= "smatias.jean@gmail.com"},
    { name="Pieter Gijsbers", email="p.gijsbers@tue.nl"},
]
readme = "README.md"

requires-python = ">=3.11"

dependencies = [
  "requests",
  "pandas",
  "aiohttp",
  "asyncio",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "responses",
    "aioresponses",
    "pytest",
    "pytest-asyncio",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "1.0.2"
#update_changelog_on_bump = true
version_files = ["pyproject.toml:version", "src/aiod/__version__.py"]
#changelog_start_rev = "1.0.0"

