[tool.poetry]
name = "aiod_sdk"
version = "0.1.0"
description = "Python SDK for the AIoD metadata catalogue"
authors = ["Jean Matias <smatias.jean@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
requests = "^2.31.0"
pandas = "^2.2.1"
aiohttp = "^3.9.4"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.5.0"
responses = "^0.25.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
